version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: powerpod
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_volume: {}
