//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::clusters::Entity as Clusters;
pub use super::namespaces::Entity as Namespaces;
pub use super::workload_types::Entity as WorkloadTypes;
